export const PROFILE_ROUTE = '/profile';
export const PURCHASES_PROFILE_ROUTE = '/profile/purchases';
export const FAVORITES_PROFILE_ROUTE = '/profile/favorites';
export const WATCHED_PROFILE_ROUTE = '/profile/watched';
export const SUBSCRIPTIONS_PROFILE_ROUTE = '/profile/subscriptions';
export const PAYMENT_PROFILE_ROUTE = '/profile/payment';
export const REFERRAL_PROFILE_ROUTE = '/profile/referral';
export const SETTINGS_PROFILE_ROUTE = '/profile/settings';
export const HELP_PROFILE_ROUTE =
  'https://ask.ivi.ru/?_gl=1*1su3zc7*_ga*MTg0MzcwNzU1LjE2ODEyMTQ2Nzg.*_ga_GETQ4387MJ*MTY4MTkwNjIyOS4xNS4xLjE2ODE5MDkzMDIuNi4wLjA.';
